// video data

export const videoData = [
  {
    video: require("../../storage/videos/video1.mp4"),
    postProfile: require("../../storage/images/profile1.png"),
    title: "johndoe",
    description: "Feel the beauty of nature",
    likes: "245k",
    isLiked: false,
  },
  {
    video: require("../../storage/videos/video2.mp4"),
    postProfile: require("../../storage/images/profile2.png"),

    title: "perry_24",
    description: "im back",
    likes: "25k",
    isLiked: false,
  },
  {
    video: require("../../storage/videos/video3.mp4"),
    postProfile: require("../../storage/images/profile3.png"),
    title: "daniel031",
    description: "first video in a while",
    likes: "5k",
    isLiked: false,
  },
  {
    video: require("../../storage/videos/video4.mp4"),
    postProfile: require("../../storage/images/profile4.png"),

    title: "codewme",
    description: "what an awesome video",
    likes: "45k",
    isLiked: false,
  },
];

// friends profile data

export const FriendsProfileData = [
  {
    name: "Ram_Charan",
    accountName: "Ram Charan",
    profileImage: require("../../storage/images/profile5.jpg"),
    posts: 59,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: "theterminator",
    accountName: "The Terminator",
    profileImage: require("../../storage/images/profile6.jpg"),
    posts: 59,
    followers: 652,
    following: 43,
    follow: false,
  },
  {
    name: "lily_beach",
    accountName: "Lily Beach",
    profileImage: require("../../storage/images/profile7.jpg"),
    posts: 59,
    followers: 4124,
    following: 43,
    follow: false,
  },
  {
    name: "thomas_marc",
    accountName: "Thomas Marc",
    profileImage: require("../../storage/images/profile8.png"),
    posts: 19,
    followers: 652,
    following: 432,
    follow: false,
  },
  {
    name: "john_doe",
    accountName: "John Doe",
    profileImage: require("../../storage/images/profile4.png"),
    posts: 593,
    followers: 65423,
    following: 4322,
    follow: false,
  },
  {
    name: "codewme",
    accountName: "Code With Me",
    profileImage: require("../../storage/images/profile3.png"),
    posts: 12,
    followers: 90921,
    following: 43,
    follow: false,
  },
  {
    name: "daisy24",
    accountName: "Daisy Winter",
    profileImage: require("../../storage/images/profile2.png"),
    posts: 52,
    followers: 11,
    following: 412,
    follow: false,
  },
  {
    name: "frank_new",
    accountName: "Frank New",
    profileImage: require("../../storage/images/profile1.png"),
    posts: 19,
    followers: 652,
    following: 432,
    follow: false,
  },
  {
    name: "thomas_marc",
    accountName: "Thomas Marc",
    profileImage: require("../../storage/images/profile8.png"),
    posts: 19,
    followers: 652,
    following: 432,
    follow: false,
  },
  {
    name: "john_smith",
    accountName: "John Smith",
    profileImage: require("../../storage/images/profile12.jpg"),
    posts: 53,
    followers: 6523,
    following: 32,
    follow: false,
  },
  {
    name: "sport_person",
    accountName: "Sport Person",
    profileImage: require("../../storage/images/profile11.jpg"),
    posts: 122,
    followers: 9092,
    following: 3,
    follow: false,
  },
  {
    name: "nobody_123123",
    accountName: "Nobody",
    profileImage: require("../../storage/images/profile10.jpg"),
    posts: 0,
    followers: 0,
    following: 8122,
    follow: false,
  },
  {
    name: "coolman123",
    accountName: "Cool Man",
    profileImage: require("../../storage/images/profile9.jpg"),
    posts: 9,
    followers: 52,
    following: 4322,
    follow: false,
  },
];
